//
//  GroupWorker.swift
//  Meetup-CleanSwift
//
//  Created by Alejandro Orozco Builes on 11/10/18.
//  Copyright (c) 2018 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GroupWorker: IGroupsAPI
{
  var groupsAPI: IGroupsAPI?
  
  func getGroups(with topic: Group.SearchGroup.Request, completionHandler: @escaping ([Group.SearchGroup.Response]?, NSError?) -> Void) {
    groupsAPI = GroupsAPI()
    groupsAPI?.getGroups(with: topic, completionHandler: { (response, error) in
      completionHandler(response, error)
    })
  }
  
}
