//
//  GroupDetailPresenter.swift
//  Meetup-CleanSwift
//
//  Created by Alejandro Orozco Builes on 11/11/18.
//  Copyright (c) 2018 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GroupDetailPresentationLogic
{
  func presentGroupDetail(detail: GroupDetail.ShowDetail.ViewModel)
}

class GroupDetailPresenter: GroupDetailPresentationLogic
{
  weak var viewController: GroupDetailDisplayLogic?
  
  // MARK: - Show Detail
  
  func presentGroupDetail(detail: GroupDetail.ShowDetail.ViewModel) {
    viewController?.displayGroupDetail(viewModel: detail)
  }
}
