//
//  GroupDetailWorker.swift
//  Meetup-CleanSwift
//
//  Created by Alejandro Orozco Builes on 11/11/18.
//  Copyright (c) 2018 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GroupDetailWorker
{
  func doSomeWork()
  {
  }
}
