//
//  GroupDetailRouter.swift
//  Meetup-CleanSwift
//
//  Created by Alejandro Orozco Builes on 11/11/18.
//  Copyright (c) 2018 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GroupDetailRoutingLogic
{
  //func routeToGroupDetail(segue: UIStoryboardSegue?)
}

protocol GroupDetailDataPassing
{
  var dataStore: GroupDetailDataStore? { get }
}

class GroupDetailRouter: NSObject, GroupDetailRoutingLogic, GroupDetailDataPassing
{
  weak var viewController: GroupDetailViewController?
  var dataStore: GroupDetailDataStore?
  
  // MARK: Routing
  
  //func routeToGroupDetail(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: GroupDetailViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: GroupDetailDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
