//
//  GroupWorkerTests.swift
//  Meetup-CleanSwift
//
//  Created by Alejandro Orozco Builes on 11/13/18.
//  Copyright (c) 2018 Alejandro Orozco Builes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Meetup_CleanSwift
import XCTest

class GroupWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: GroupWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupGroupWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupGroupWorker()
  {
    sut = GroupWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
